//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILMY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FILMY()
        {
            this.SEANSE = new HashSet<SEANSE>();
        }
    
        public int ID_FILMU { get; set; }
        public string TYTUL { get; set; }
        public string GATUNEK { get; set; }
        public string REZYSER { get; set; }
        public decimal CZAS_TRWANIA { get; set; }
        public decimal OCENA { get; set; }
        public Nullable<decimal> ILOSC_GLOSOW { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEANSE> SEANSE { get; set; }
    }
}
