//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class KLIENCI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KLIENCI()
        {
            this.ZAMOWIENIA = new HashSet<ZAMOWIENIA>();
        }
    
        public int ID_KLIENTA { get; set; }
        public string EMAIL { get; set; }
        public string HASLO { get; set; }
    
        public virtual DANE_OSOBOWE DANE_OSOBOWE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZAMOWIENIA> ZAMOWIENIA { get; set; }
    }
}
