CREATE TABLE FILMY (
    ID_FILMU INT PRIMARY KEY,
    TYTUL VARCHAR(32) NOT NULL,
    GATUNEK VARCHAR(16) NOT NULL,
    REZYSER VARCHAR(32) NOT NULL,
	CZAS_TRWANIA NUMERIC (3,0) NOT NULL,
    OCENA NUMERIC (2,1) NOT NULL,
    ILOSC_GLOSOW NUMERIC (5,0)
	)

CREATE TABLE SEANSE (
    ID_SEANSU INT PRIMARY KEY,
    ID_FILMU INT REFERENCES FILMY(ID_FILMU),
    DATA_SEANSU DATE NOT NULL,
    CENA NUMERIC (4,2) NOT NULL
);
CREATE TABLE DANE_OSOBOWE (
    EMAIL VARCHAR(32) PRIMARY KEY,
    IMIE VARCHAR(12) NOT NULL,
    NAZWISKO VARCHAR(16) NOT NULL,
    NUMER_TEL NUMERIC (9,0) NOT NULL
);

CREATE TABLE KLIENCI (
    ID_KLIENTA INT PRIMARY KEY,
    EMAIL VARCHAR(32) REFERENCES DANE_OSOBOWE(EMAIL),
    HASLO VARCHAR(32) NOT NULL
);

CREATE TABLE ZAMOWIENIA (
    ID_ZAMOWIENIA INT PRIMARY KEY,
    ID_KLIENTA INT REFERENCES KLIENCI(ID_KLIENTA),
    ID_SEANSU INT REFERENCES SEANSE(ID_SEANSU),
);




  
